name: Lint
#
# This workflow lints the UI library and reports back any suggested fixes
#

on:
    workflow_dispatch:
    workflow_call:

permissions:
    contents: read
    pull-requests: write

defaults:
    run:
        shell: bash

jobs:
    # --- Lint pre-compiled assets for consistency --- #
    eslint:
        name: Eslint
        runs-on: ubuntu-latest
        timeout-minutes: 5
        outputs:
            eslint_diff_files: ${{ steps.changed-files.outputs.eslint_diff_files }}
        steps:
            # install but don't build - we're linting pre-compiled assets
            - name: Check out code
              uses: actions/checkout@v4

            - name: Setup Job and Install Dependencies
              uses: ./.github/actions/setup-job
              with:
                  skip-build: true

            - name: Check for changed files
              id: changed-files
              run: |
                  echo "eslint=$(git diff --name-only --diff-filter=d -- "projects/documentation/**/*.ts" "packages/**/*.ts" "tools/**/*.ts" | xargs)" >> $GITHUB_OUTPUT

            - name: Run eslint on packages and stories
              uses: reviewdog/action-eslint@v1.33.0
              if: ${{ steps.changed-files.outputs.eslint != '' }}
              with:
                  fail_level: error
                  level: error
                  reporter: github-pr-review
                  filter_mode: diff_context
                  eslint_flags: '${{ steps.changed-files.outputs.eslint }}'

    # --- Lint pre-compiled assets for consistency --- #
    stylelint:
        name: Stylelint
        runs-on: ubuntu-latest
        timeout-minutes: 5
        outputs:
            stylelint_diff_files: ${{ steps.changed-files.outputs.stylelint_diff_files }}
        steps:
            # install but don't build - we're linting pre-compiled assets
            - name: Check out code
              uses: actions/checkout@v4

            - name: Setup Job and Install Dependencies
              uses: ./.github/actions/setup-job
              with:
                  skip-build: true

            - name: Check for changed files
              id: changed-files
              run: |
                  echo "stylelint=$(git diff --name-only --diff-filter=d -- "packages/**/*.css" "tools/**/*.css" | xargs)" >> $GITHUB_OUTPUT

            - name: Lint component styles
              uses: reviewdog/action-stylelint@v1.30.0
              if: ${{ steps.changed-files.outputs.stylelint != '' }}
              with:
                  fail_level: error
                  filter_mode: diff_context
                  level: error
                  reporter: github-pr-review
                  stylelint_input: '${{ steps.changed-files.outputs.stylelint }}'
                  stylelint_config: '${{ github.workspace }}/.stylelintrc.json'
